import Header from "@/components/Header";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";

const nunito_Sans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_Sans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
